name: Deploy Intance on AWS 

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Show environment (debug)
        run: echo "AWS region is $AWS_REGION"

      - name: Run EC2 setup script
        env:
          AMI_ID: ${{ secrets.AMI_ID }}
          KEY_NAME: ${{ secrets.KEY_NAME }}
          SECURITY_GROUP: ${{ secrets.SECURITY_GROUP }}
          SUBNET_ID: ${{ secrets.SUBNET_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: bash ./Launch_Instance.sh
